export { default as Home } from './Home';
export { default as Products } from './Products';
export { default as Product } from './Product';
export { default as AboutPage } from './AboutPage';
export { default as ContactPage } from './ContactPage';
export { default as Cart } from './Cart';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Checkout } from './Checkout';
export { default as PageNotFound } from './PageNotFound';
export { default as Dashboard } from './Dashboard';
export { default as ProductsList } from './ProductsList';
export { default as AddProduct } from './AddProduct';
export { default as PutProduct } from './PutProduct';
export { default as SuppliersList } from './SuppliersList';
export { default as AddSupplier } from './AddSupplier';
export { default as PutSupplier } from './PutSupplier';
export { default as Orders } from './Orders';
export { default as ProductDetails} from './ProductDetailDash';
export { default as Statistics} from './Statistics';
export { default as Users } from './Users';
